<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.1.39" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LendingSolution.Core\LendingSolution.Core.csproj" />
    <ProjectReference Include="..\LendingSolution.Infrastructure\LendingSolution.Infrastructure.csproj" />
  </ItemGroup>

</Project>